#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FORM_CSDL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QUAN_LI_CHUYEN_BAY")]
	public partial class DataQLCBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertHANHKHACH(HANHKHACH instance);
    partial void UpdateHANHKHACH(HANHKHACH instance);
    partial void DeleteHANHKHACH(HANHKHACH instance);
    partial void InsertKHANANG(KHANANG instance);
    partial void UpdateKHANANG(KHANANG instance);
    partial void DeleteKHANANG(KHANANG instance);
    partial void InsertLICHBAY(LICHBAY instance);
    partial void UpdateLICHBAY(LICHBAY instance);
    partial void DeleteLICHBAY(LICHBAY instance);
    partial void InsertLOAIMAYBAY(LOAIMAYBAY instance);
    partial void UpdateLOAIMAYBAY(LOAIMAYBAY instance);
    partial void DeleteLOAIMAYBAY(LOAIMAYBAY instance);
    partial void InsertMAYBAY(MAYBAY instance);
    partial void UpdateMAYBAY(MAYBAY instance);
    partial void DeleteMAYBAY(MAYBAY instance);
    partial void InsertPHICONG(PHICONG instance);
    partial void UpdatePHICONG(PHICONG instance);
    partial void DeletePHICONG(PHICONG instance);
    partial void InsertVE(VE instance);
    partial void UpdateVE(VE instance);
    partial void DeleteVE(VE instance);
    #endregion
		
		public DataQLCBDataContext() : 
				base(global::FORM_CSDL.Properties.Settings.Default.QUAN_LI_CHUYEN_BAYConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLCBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLCBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLCBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLCBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<HANHKHACH> HANHKHACHes
		{
			get
			{
				return this.GetTable<HANHKHACH>();
			}
		}
		
		public System.Data.Linq.Table<KHANANG> KHANANGs
		{
			get
			{
				return this.GetTable<KHANANG>();
			}
		}
		
		public System.Data.Linq.Table<LICHBAY> LICHBAYs
		{
			get
			{
				return this.GetTable<LICHBAY>();
			}
		}
		
		public System.Data.Linq.Table<LOAIMAYBAY> LOAIMAYBAYs
		{
			get
			{
				return this.GetTable<LOAIMAYBAY>();
			}
		}
		
		public System.Data.Linq.Table<MAYBAY> MAYBAYs
		{
			get
			{
				return this.GetTable<MAYBAY>();
			}
		}
		
		public System.Data.Linq.Table<PHICONG> PHICONGs
		{
			get
			{
				return this.GetTable<PHICONG>();
			}
		}
		
		public System.Data.Linq.Table<VE> VEs
		{
			get
			{
				return this.GetTable<VE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HANHKHACH")]
	public partial class HANHKHACH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CMND_HK;
		
		private string _HotenHK;
		
		private System.Nullable<System.DateTime> _NgaySinhHK;
		
		private string _DiachiHK;
		
		private string _SdtHK;
		
		private EntitySet<VE> _VEs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCMND_HKChanging(string value);
    partial void OnCMND_HKChanged();
    partial void OnHotenHKChanging(string value);
    partial void OnHotenHKChanged();
    partial void OnNgaySinhHKChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhHKChanged();
    partial void OnDiachiHKChanging(string value);
    partial void OnDiachiHKChanged();
    partial void OnSdtHKChanging(string value);
    partial void OnSdtHKChanged();
    #endregion
		
		public HANHKHACH()
		{
			this._VEs = new EntitySet<VE>(new Action<VE>(this.attach_VEs), new Action<VE>(this.detach_VEs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND_HK", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CMND_HK
		{
			get
			{
				return this._CMND_HK;
			}
			set
			{
				if ((this._CMND_HK != value))
				{
					this.OnCMND_HKChanging(value);
					this.SendPropertyChanging();
					this._CMND_HK = value;
					this.SendPropertyChanged("CMND_HK");
					this.OnCMND_HKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HotenHK", DbType="VarChar(50)")]
		public string HotenHK
		{
			get
			{
				return this._HotenHK;
			}
			set
			{
				if ((this._HotenHK != value))
				{
					this.OnHotenHKChanging(value);
					this.SendPropertyChanging();
					this._HotenHK = value;
					this.SendPropertyChanged("HotenHK");
					this.OnHotenHKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinhHK", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinhHK
		{
			get
			{
				return this._NgaySinhHK;
			}
			set
			{
				if ((this._NgaySinhHK != value))
				{
					this.OnNgaySinhHKChanging(value);
					this.SendPropertyChanging();
					this._NgaySinhHK = value;
					this.SendPropertyChanged("NgaySinhHK");
					this.OnNgaySinhHKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiachiHK", DbType="VarChar(50)")]
		public string DiachiHK
		{
			get
			{
				return this._DiachiHK;
			}
			set
			{
				if ((this._DiachiHK != value))
				{
					this.OnDiachiHKChanging(value);
					this.SendPropertyChanging();
					this._DiachiHK = value;
					this.SendPropertyChanged("DiachiHK");
					this.OnDiachiHKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SdtHK", DbType="VarChar(11)")]
		public string SdtHK
		{
			get
			{
				return this._SdtHK;
			}
			set
			{
				if ((this._SdtHK != value))
				{
					this.OnSdtHKChanging(value);
					this.SendPropertyChanging();
					this._SdtHK = value;
					this.SendPropertyChanged("SdtHK");
					this.OnSdtHKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HANHKHACH_VE", Storage="_VEs", ThisKey="CMND_HK", OtherKey="CMND_HK")]
		public EntitySet<VE> VEs
		{
			get
			{
				return this._VEs;
			}
			set
			{
				this._VEs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VEs(VE entity)
		{
			this.SendPropertyChanging();
			entity.HANHKHACH = this;
		}
		
		private void detach_VEs(VE entity)
		{
			this.SendPropertyChanging();
			entity.HANHKHACH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHANANG")]
	public partial class KHANANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAPC;
		
		private string _MaLoaiMayBay;
		
		private EntityRef<LOAIMAYBAY> _LOAIMAYBAY;
		
		private EntityRef<PHICONG> _PHICONG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPCChanging(string value);
    partial void OnMAPCChanged();
    partial void OnMaLoaiMayBayChanging(string value);
    partial void OnMaLoaiMayBayChanged();
    #endregion
		
		public KHANANG()
		{
			this._LOAIMAYBAY = default(EntityRef<LOAIMAYBAY>);
			this._PHICONG = default(EntityRef<PHICONG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPC", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAPC
		{
			get
			{
				return this._MAPC;
			}
			set
			{
				if ((this._MAPC != value))
				{
					if (this._PHICONG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAPCChanging(value);
					this.SendPropertyChanging();
					this._MAPC = value;
					this.SendPropertyChanged("MAPC");
					this.OnMAPCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiMayBay", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoaiMayBay
		{
			get
			{
				return this._MaLoaiMayBay;
			}
			set
			{
				if ((this._MaLoaiMayBay != value))
				{
					if (this._LOAIMAYBAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiMayBayChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiMayBay = value;
					this.SendPropertyChanged("MaLoaiMayBay");
					this.OnMaLoaiMayBayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIMAYBAY_KHANANG", Storage="_LOAIMAYBAY", ThisKey="MaLoaiMayBay", OtherKey="MaLoaiMayBay", IsForeignKey=true)]
		public LOAIMAYBAY LOAIMAYBAY
		{
			get
			{
				return this._LOAIMAYBAY.Entity;
			}
			set
			{
				LOAIMAYBAY previousValue = this._LOAIMAYBAY.Entity;
				if (((previousValue != value) 
							|| (this._LOAIMAYBAY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAIMAYBAY.Entity = null;
						previousValue.KHANANGs.Remove(this);
					}
					this._LOAIMAYBAY.Entity = value;
					if ((value != null))
					{
						value.KHANANGs.Add(this);
						this._MaLoaiMayBay = value.MaLoaiMayBay;
					}
					else
					{
						this._MaLoaiMayBay = default(string);
					}
					this.SendPropertyChanged("LOAIMAYBAY");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHICONG_KHANANG", Storage="_PHICONG", ThisKey="MAPC", OtherKey="MaPC", IsForeignKey=true)]
		public PHICONG PHICONG
		{
			get
			{
				return this._PHICONG.Entity;
			}
			set
			{
				PHICONG previousValue = this._PHICONG.Entity;
				if (((previousValue != value) 
							|| (this._PHICONG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHICONG.Entity = null;
						previousValue.KHANANGs.Remove(this);
					}
					this._PHICONG.Entity = value;
					if ((value != null))
					{
						value.KHANANGs.Add(this);
						this._MAPC = value.MaPC;
					}
					else
					{
						this._MAPC = default(string);
					}
					this.SendPropertyChanged("PHICONG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LICHBAY")]
	public partial class LICHBAY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCB;
		
		private string _SoHieu;
		
		private System.DateTime _ThoiGianCatCanh;
		
		private System.DateTime _ThoiGianHaCanh;
		
		private string _SanBayDi;
		
		private string _SanBayDen;
		
		private string _TrangThaiMayBay;
		
		private System.Nullable<int> _So_ghe_con_trong;
		
		private string _MaPC;
		
		private EntitySet<VE> _VEs;
		
		private EntityRef<MAYBAY> _MAYBAY;
		
		private EntityRef<PHICONG> _PHICONG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCBChanging(string value);
    partial void OnMaCBChanged();
    partial void OnSoHieuChanging(string value);
    partial void OnSoHieuChanged();
    partial void OnThoiGianCatCanhChanging(System.DateTime value);
    partial void OnThoiGianCatCanhChanged();
    partial void OnThoiGianHaCanhChanging(System.DateTime value);
    partial void OnThoiGianHaCanhChanged();
    partial void OnSanBayDiChanging(string value);
    partial void OnSanBayDiChanged();
    partial void OnSanBayDenChanging(string value);
    partial void OnSanBayDenChanged();
    partial void OnTrangThaiMayBayChanging(string value);
    partial void OnTrangThaiMayBayChanged();
    partial void OnSo_ghe_con_trongChanging(System.Nullable<int> value);
    partial void OnSo_ghe_con_trongChanged();
    partial void OnMaPCChanging(string value);
    partial void OnMaPCChanged();
    #endregion
		
		public LICHBAY()
		{
			this._VEs = new EntitySet<VE>(new Action<VE>(this.attach_VEs), new Action<VE>(this.detach_VEs));
			this._MAYBAY = default(EntityRef<MAYBAY>);
			this._PHICONG = default(EntityRef<PHICONG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCB", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCB
		{
			get
			{
				return this._MaCB;
			}
			set
			{
				if ((this._MaCB != value))
				{
					this.OnMaCBChanging(value);
					this.SendPropertyChanging();
					this._MaCB = value;
					this.SendPropertyChanged("MaCB");
					this.OnMaCBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoHieu", DbType="VarChar(10)")]
		public string SoHieu
		{
			get
			{
				return this._SoHieu;
			}
			set
			{
				if ((this._SoHieu != value))
				{
					if (this._MAYBAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSoHieuChanging(value);
					this.SendPropertyChanging();
					this._SoHieu = value;
					this.SendPropertyChanged("SoHieu");
					this.OnSoHieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianCatCanh", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime ThoiGianCatCanh
		{
			get
			{
				return this._ThoiGianCatCanh;
			}
			set
			{
				if ((this._ThoiGianCatCanh != value))
				{
					this.OnThoiGianCatCanhChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianCatCanh = value;
					this.SendPropertyChanged("ThoiGianCatCanh");
					this.OnThoiGianCatCanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianHaCanh", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime ThoiGianHaCanh
		{
			get
			{
				return this._ThoiGianHaCanh;
			}
			set
			{
				if ((this._ThoiGianHaCanh != value))
				{
					this.OnThoiGianHaCanhChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianHaCanh = value;
					this.SendPropertyChanged("ThoiGianHaCanh");
					this.OnThoiGianHaCanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SanBayDi", DbType="VarChar(50)")]
		public string SanBayDi
		{
			get
			{
				return this._SanBayDi;
			}
			set
			{
				if ((this._SanBayDi != value))
				{
					this.OnSanBayDiChanging(value);
					this.SendPropertyChanging();
					this._SanBayDi = value;
					this.SendPropertyChanged("SanBayDi");
					this.OnSanBayDiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SanBayDen", DbType="VarChar(50)")]
		public string SanBayDen
		{
			get
			{
				return this._SanBayDen;
			}
			set
			{
				if ((this._SanBayDen != value))
				{
					this.OnSanBayDenChanging(value);
					this.SendPropertyChanging();
					this._SanBayDen = value;
					this.SendPropertyChanged("SanBayDen");
					this.OnSanBayDenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiMayBay", DbType="VarChar(30)")]
		public string TrangThaiMayBay
		{
			get
			{
				return this._TrangThaiMayBay;
			}
			set
			{
				if ((this._TrangThaiMayBay != value))
				{
					this.OnTrangThaiMayBayChanging(value);
					this.SendPropertyChanging();
					this._TrangThaiMayBay = value;
					this.SendPropertyChanged("TrangThaiMayBay");
					this.OnTrangThaiMayBayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_ghe_con_trong", DbType="Int")]
		public System.Nullable<int> So_ghe_con_trong
		{
			get
			{
				return this._So_ghe_con_trong;
			}
			set
			{
				if ((this._So_ghe_con_trong != value))
				{
					this.OnSo_ghe_con_trongChanging(value);
					this.SendPropertyChanging();
					this._So_ghe_con_trong = value;
					this.SendPropertyChanged("So_ghe_con_trong");
					this.OnSo_ghe_con_trongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPC", DbType="VarChar(10)")]
		public string MaPC
		{
			get
			{
				return this._MaPC;
			}
			set
			{
				if ((this._MaPC != value))
				{
					if (this._PHICONG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPCChanging(value);
					this.SendPropertyChanging();
					this._MaPC = value;
					this.SendPropertyChanged("MaPC");
					this.OnMaPCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LICHBAY_VE", Storage="_VEs", ThisKey="MaCB,ThoiGianCatCanh,ThoiGianHaCanh", OtherKey="MaCB,ThoiGianCatCanh,ThoiGianHaCanh")]
		public EntitySet<VE> VEs
		{
			get
			{
				return this._VEs;
			}
			set
			{
				this._VEs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAYBAY_LICHBAY", Storage="_MAYBAY", ThisKey="SoHieu", OtherKey="SoHieu", IsForeignKey=true)]
		public MAYBAY MAYBAY
		{
			get
			{
				return this._MAYBAY.Entity;
			}
			set
			{
				MAYBAY previousValue = this._MAYBAY.Entity;
				if (((previousValue != value) 
							|| (this._MAYBAY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MAYBAY.Entity = null;
						previousValue.LICHBAYs.Remove(this);
					}
					this._MAYBAY.Entity = value;
					if ((value != null))
					{
						value.LICHBAYs.Add(this);
						this._SoHieu = value.SoHieu;
					}
					else
					{
						this._SoHieu = default(string);
					}
					this.SendPropertyChanged("MAYBAY");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHICONG_LICHBAY", Storage="_PHICONG", ThisKey="MaPC", OtherKey="MaPC", IsForeignKey=true)]
		public PHICONG PHICONG
		{
			get
			{
				return this._PHICONG.Entity;
			}
			set
			{
				PHICONG previousValue = this._PHICONG.Entity;
				if (((previousValue != value) 
							|| (this._PHICONG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHICONG.Entity = null;
						previousValue.LICHBAYs.Remove(this);
					}
					this._PHICONG.Entity = value;
					if ((value != null))
					{
						value.LICHBAYs.Add(this);
						this._MaPC = value.MaPC;
					}
					else
					{
						this._MaPC = default(string);
					}
					this.SendPropertyChanged("PHICONG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VEs(VE entity)
		{
			this.SendPropertyChanging();
			entity.LICHBAY = this;
		}
		
		private void detach_VEs(VE entity)
		{
			this.SendPropertyChanging();
			entity.LICHBAY = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIMAYBAY")]
	public partial class LOAIMAYBAY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoaiMayBay;
		
		private string _HangSanXuat;
		
		private EntitySet<KHANANG> _KHANANGs;
		
		private EntitySet<MAYBAY> _MAYBAYs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiMayBayChanging(string value);
    partial void OnMaLoaiMayBayChanged();
    partial void OnHangSanXuatChanging(string value);
    partial void OnHangSanXuatChanged();
    #endregion
		
		public LOAIMAYBAY()
		{
			this._KHANANGs = new EntitySet<KHANANG>(new Action<KHANANG>(this.attach_KHANANGs), new Action<KHANANG>(this.detach_KHANANGs));
			this._MAYBAYs = new EntitySet<MAYBAY>(new Action<MAYBAY>(this.attach_MAYBAYs), new Action<MAYBAY>(this.detach_MAYBAYs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiMayBay", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoaiMayBay
		{
			get
			{
				return this._MaLoaiMayBay;
			}
			set
			{
				if ((this._MaLoaiMayBay != value))
				{
					this.OnMaLoaiMayBayChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiMayBay = value;
					this.SendPropertyChanged("MaLoaiMayBay");
					this.OnMaLoaiMayBayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HangSanXuat", DbType="VarChar(50)")]
		public string HangSanXuat
		{
			get
			{
				return this._HangSanXuat;
			}
			set
			{
				if ((this._HangSanXuat != value))
				{
					this.OnHangSanXuatChanging(value);
					this.SendPropertyChanging();
					this._HangSanXuat = value;
					this.SendPropertyChanged("HangSanXuat");
					this.OnHangSanXuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIMAYBAY_KHANANG", Storage="_KHANANGs", ThisKey="MaLoaiMayBay", OtherKey="MaLoaiMayBay")]
		public EntitySet<KHANANG> KHANANGs
		{
			get
			{
				return this._KHANANGs;
			}
			set
			{
				this._KHANANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIMAYBAY_MAYBAY", Storage="_MAYBAYs", ThisKey="MaLoaiMayBay", OtherKey="MaLoaiMayBay")]
		public EntitySet<MAYBAY> MAYBAYs
		{
			get
			{
				return this._MAYBAYs;
			}
			set
			{
				this._MAYBAYs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KHANANGs(KHANANG entity)
		{
			this.SendPropertyChanging();
			entity.LOAIMAYBAY = this;
		}
		
		private void detach_KHANANGs(KHANANG entity)
		{
			this.SendPropertyChanging();
			entity.LOAIMAYBAY = null;
		}
		
		private void attach_MAYBAYs(MAYBAY entity)
		{
			this.SendPropertyChanging();
			entity.LOAIMAYBAY = this;
		}
		
		private void detach_MAYBAYs(MAYBAY entity)
		{
			this.SendPropertyChanging();
			entity.LOAIMAYBAY = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAYBAY")]
	public partial class MAYBAY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SoHieu;
		
		private string _MaLoaiMayBay;
		
		private System.Nullable<int> _SoLuongGheToiDa;
		
		private EntitySet<LICHBAY> _LICHBAYs;
		
		private EntityRef<LOAIMAYBAY> _LOAIMAYBAY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSoHieuChanging(string value);
    partial void OnSoHieuChanged();
    partial void OnMaLoaiMayBayChanging(string value);
    partial void OnMaLoaiMayBayChanged();
    partial void OnSoLuongGheToiDaChanging(System.Nullable<int> value);
    partial void OnSoLuongGheToiDaChanged();
    #endregion
		
		public MAYBAY()
		{
			this._LICHBAYs = new EntitySet<LICHBAY>(new Action<LICHBAY>(this.attach_LICHBAYs), new Action<LICHBAY>(this.detach_LICHBAYs));
			this._LOAIMAYBAY = default(EntityRef<LOAIMAYBAY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoHieu", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SoHieu
		{
			get
			{
				return this._SoHieu;
			}
			set
			{
				if ((this._SoHieu != value))
				{
					this.OnSoHieuChanging(value);
					this.SendPropertyChanging();
					this._SoHieu = value;
					this.SendPropertyChanged("SoHieu");
					this.OnSoHieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiMayBay", DbType="VarChar(10)")]
		public string MaLoaiMayBay
		{
			get
			{
				return this._MaLoaiMayBay;
			}
			set
			{
				if ((this._MaLoaiMayBay != value))
				{
					if (this._LOAIMAYBAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiMayBayChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiMayBay = value;
					this.SendPropertyChanged("MaLoaiMayBay");
					this.OnMaLoaiMayBayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongGheToiDa", DbType="Int")]
		public System.Nullable<int> SoLuongGheToiDa
		{
			get
			{
				return this._SoLuongGheToiDa;
			}
			set
			{
				if ((this._SoLuongGheToiDa != value))
				{
					this.OnSoLuongGheToiDaChanging(value);
					this.SendPropertyChanging();
					this._SoLuongGheToiDa = value;
					this.SendPropertyChanged("SoLuongGheToiDa");
					this.OnSoLuongGheToiDaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAYBAY_LICHBAY", Storage="_LICHBAYs", ThisKey="SoHieu", OtherKey="SoHieu")]
		public EntitySet<LICHBAY> LICHBAYs
		{
			get
			{
				return this._LICHBAYs;
			}
			set
			{
				this._LICHBAYs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIMAYBAY_MAYBAY", Storage="_LOAIMAYBAY", ThisKey="MaLoaiMayBay", OtherKey="MaLoaiMayBay", IsForeignKey=true)]
		public LOAIMAYBAY LOAIMAYBAY
		{
			get
			{
				return this._LOAIMAYBAY.Entity;
			}
			set
			{
				LOAIMAYBAY previousValue = this._LOAIMAYBAY.Entity;
				if (((previousValue != value) 
							|| (this._LOAIMAYBAY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAIMAYBAY.Entity = null;
						previousValue.MAYBAYs.Remove(this);
					}
					this._LOAIMAYBAY.Entity = value;
					if ((value != null))
					{
						value.MAYBAYs.Add(this);
						this._MaLoaiMayBay = value.MaLoaiMayBay;
					}
					else
					{
						this._MaLoaiMayBay = default(string);
					}
					this.SendPropertyChanged("LOAIMAYBAY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LICHBAYs(LICHBAY entity)
		{
			this.SendPropertyChanging();
			entity.MAYBAY = this;
		}
		
		private void detach_LICHBAYs(LICHBAY entity)
		{
			this.SendPropertyChanging();
			entity.MAYBAY = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHICONG")]
	public partial class PHICONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPC;
		
		private string _TenPC;
		
		private string _DiaChiPC;
		
		private string _SDT_Phi_cong;
		
		private System.Nullable<double> _Luong_Phi_cong;
		
		private System.Nullable<double> _Gio_bay;
		
		private EntitySet<KHANANG> _KHANANGs;
		
		private EntitySet<LICHBAY> _LICHBAYs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPCChanging(string value);
    partial void OnMaPCChanged();
    partial void OnTenPCChanging(string value);
    partial void OnTenPCChanged();
    partial void OnDiaChiPCChanging(string value);
    partial void OnDiaChiPCChanged();
    partial void OnSDT_Phi_congChanging(string value);
    partial void OnSDT_Phi_congChanged();
    partial void OnLuong_Phi_congChanging(System.Nullable<double> value);
    partial void OnLuong_Phi_congChanged();
    partial void OnGio_bayChanging(System.Nullable<double> value);
    partial void OnGio_bayChanged();
    #endregion
		
		public PHICONG()
		{
			this._KHANANGs = new EntitySet<KHANANG>(new Action<KHANANG>(this.attach_KHANANGs), new Action<KHANANG>(this.detach_KHANANGs));
			this._LICHBAYs = new EntitySet<LICHBAY>(new Action<LICHBAY>(this.attach_LICHBAYs), new Action<LICHBAY>(this.detach_LICHBAYs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPC", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPC
		{
			get
			{
				return this._MaPC;
			}
			set
			{
				if ((this._MaPC != value))
				{
					this.OnMaPCChanging(value);
					this.SendPropertyChanging();
					this._MaPC = value;
					this.SendPropertyChanged("MaPC");
					this.OnMaPCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPC", DbType="VarChar(30)")]
		public string TenPC
		{
			get
			{
				return this._TenPC;
			}
			set
			{
				if ((this._TenPC != value))
				{
					this.OnTenPCChanging(value);
					this.SendPropertyChanging();
					this._TenPC = value;
					this.SendPropertyChanged("TenPC");
					this.OnTenPCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiPC", DbType="VarChar(50)")]
		public string DiaChiPC
		{
			get
			{
				return this._DiaChiPC;
			}
			set
			{
				if ((this._DiaChiPC != value))
				{
					this.OnDiaChiPCChanging(value);
					this.SendPropertyChanging();
					this._DiaChiPC = value;
					this.SendPropertyChanged("DiaChiPC");
					this.OnDiaChiPCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT_Phi_cong", DbType="VarChar(11)")]
		public string SDT_Phi_cong
		{
			get
			{
				return this._SDT_Phi_cong;
			}
			set
			{
				if ((this._SDT_Phi_cong != value))
				{
					this.OnSDT_Phi_congChanging(value);
					this.SendPropertyChanging();
					this._SDT_Phi_cong = value;
					this.SendPropertyChanged("SDT_Phi_cong");
					this.OnSDT_Phi_congChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Luong_Phi_cong", DbType="Float")]
		public System.Nullable<double> Luong_Phi_cong
		{
			get
			{
				return this._Luong_Phi_cong;
			}
			set
			{
				if ((this._Luong_Phi_cong != value))
				{
					this.OnLuong_Phi_congChanging(value);
					this.SendPropertyChanging();
					this._Luong_Phi_cong = value;
					this.SendPropertyChanged("Luong_Phi_cong");
					this.OnLuong_Phi_congChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gio_bay", DbType="Float")]
		public System.Nullable<double> Gio_bay
		{
			get
			{
				return this._Gio_bay;
			}
			set
			{
				if ((this._Gio_bay != value))
				{
					this.OnGio_bayChanging(value);
					this.SendPropertyChanging();
					this._Gio_bay = value;
					this.SendPropertyChanged("Gio_bay");
					this.OnGio_bayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHICONG_KHANANG", Storage="_KHANANGs", ThisKey="MaPC", OtherKey="MAPC")]
		public EntitySet<KHANANG> KHANANGs
		{
			get
			{
				return this._KHANANGs;
			}
			set
			{
				this._KHANANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHICONG_LICHBAY", Storage="_LICHBAYs", ThisKey="MaPC", OtherKey="MaPC")]
		public EntitySet<LICHBAY> LICHBAYs
		{
			get
			{
				return this._LICHBAYs;
			}
			set
			{
				this._LICHBAYs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KHANANGs(KHANANG entity)
		{
			this.SendPropertyChanging();
			entity.PHICONG = this;
		}
		
		private void detach_KHANANGs(KHANANG entity)
		{
			this.SendPropertyChanging();
			entity.PHICONG = null;
		}
		
		private void attach_LICHBAYs(LICHBAY entity)
		{
			this.SendPropertyChanging();
			entity.PHICONG = this;
		}
		
		private void detach_LICHBAYs(LICHBAY entity)
		{
			this.SendPropertyChanging();
			entity.PHICONG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VE")]
	public partial class VE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaVe;
		
		private string _CMND_HK;
		
		private string _MaCB;
		
		private System.Nullable<System.DateTime> _ThoiGianDatVe;
		
		private System.Nullable<System.DateTime> _ThoiGianCatCanh;
		
		private System.Nullable<System.DateTime> _ThoiGianHaCanh;
		
		private System.Nullable<System.DateTime> _Ngay_can_bay;
		
		private string _Noi_Di;
		
		private string _Noi_Den;
		
		private string _TrangThaiVe;
		
		private System.Nullable<int> _SoGhe;
		
		private System.Nullable<double> _GiaVe;
		
		private System.Nullable<double> _PhiPhatsinh;
		
		private System.Nullable<double> _KhuyenMai;
		
		private System.Nullable<double> _TongGiaVe;
		
		private EntityRef<HANHKHACH> _HANHKHACH;
		
		private EntityRef<LICHBAY> _LICHBAY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaVeChanging(int value);
    partial void OnMaVeChanged();
    partial void OnCMND_HKChanging(string value);
    partial void OnCMND_HKChanged();
    partial void OnMaCBChanging(string value);
    partial void OnMaCBChanged();
    partial void OnThoiGianDatVeChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianDatVeChanged();
    partial void OnThoiGianCatCanhChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianCatCanhChanged();
    partial void OnThoiGianHaCanhChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianHaCanhChanged();
    partial void OnNgay_can_bayChanging(System.Nullable<System.DateTime> value);
    partial void OnNgay_can_bayChanged();
    partial void OnNoi_DiChanging(string value);
    partial void OnNoi_DiChanged();
    partial void OnNoi_DenChanging(string value);
    partial void OnNoi_DenChanged();
    partial void OnTrangThaiVeChanging(string value);
    partial void OnTrangThaiVeChanged();
    partial void OnSoGheChanging(System.Nullable<int> value);
    partial void OnSoGheChanged();
    partial void OnGiaVeChanging(System.Nullable<double> value);
    partial void OnGiaVeChanged();
    partial void OnPhiPhatsinhChanging(System.Nullable<double> value);
    partial void OnPhiPhatsinhChanged();
    partial void OnKhuyenMaiChanging(System.Nullable<double> value);
    partial void OnKhuyenMaiChanged();
    partial void OnTongGiaVeChanging(System.Nullable<double> value);
    partial void OnTongGiaVeChanged();
    #endregion
		
		public VE()
		{
			this._HANHKHACH = default(EntityRef<HANHKHACH>);
			this._LICHBAY = default(EntityRef<LICHBAY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaVe
		{
			get
			{
				return this._MaVe;
			}
			set
			{
				if ((this._MaVe != value))
				{
					this.OnMaVeChanging(value);
					this.SendPropertyChanging();
					this._MaVe = value;
					this.SendPropertyChanged("MaVe");
					this.OnMaVeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND_HK", DbType="VarChar(10)")]
		public string CMND_HK
		{
			get
			{
				return this._CMND_HK;
			}
			set
			{
				if ((this._CMND_HK != value))
				{
					if (this._HANHKHACH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCMND_HKChanging(value);
					this.SendPropertyChanging();
					this._CMND_HK = value;
					this.SendPropertyChanged("CMND_HK");
					this.OnCMND_HKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCB", DbType="VarChar(10)")]
		public string MaCB
		{
			get
			{
				return this._MaCB;
			}
			set
			{
				if ((this._MaCB != value))
				{
					if (this._LICHBAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCBChanging(value);
					this.SendPropertyChanging();
					this._MaCB = value;
					this.SendPropertyChanged("MaCB");
					this.OnMaCBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianDatVe", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianDatVe
		{
			get
			{
				return this._ThoiGianDatVe;
			}
			set
			{
				if ((this._ThoiGianDatVe != value))
				{
					this.OnThoiGianDatVeChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianDatVe = value;
					this.SendPropertyChanged("ThoiGianDatVe");
					this.OnThoiGianDatVeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianCatCanh", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianCatCanh
		{
			get
			{
				return this._ThoiGianCatCanh;
			}
			set
			{
				if ((this._ThoiGianCatCanh != value))
				{
					if (this._LICHBAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnThoiGianCatCanhChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianCatCanh = value;
					this.SendPropertyChanged("ThoiGianCatCanh");
					this.OnThoiGianCatCanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianHaCanh", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianHaCanh
		{
			get
			{
				return this._ThoiGianHaCanh;
			}
			set
			{
				if ((this._ThoiGianHaCanh != value))
				{
					if (this._LICHBAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnThoiGianHaCanhChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianHaCanh = value;
					this.SendPropertyChanged("ThoiGianHaCanh");
					this.OnThoiGianHaCanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_can_bay", DbType="Date")]
		public System.Nullable<System.DateTime> Ngay_can_bay
		{
			get
			{
				return this._Ngay_can_bay;
			}
			set
			{
				if ((this._Ngay_can_bay != value))
				{
					this.OnNgay_can_bayChanging(value);
					this.SendPropertyChanging();
					this._Ngay_can_bay = value;
					this.SendPropertyChanged("Ngay_can_bay");
					this.OnNgay_can_bayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noi_Di", DbType="VarChar(50)")]
		public string Noi_Di
		{
			get
			{
				return this._Noi_Di;
			}
			set
			{
				if ((this._Noi_Di != value))
				{
					this.OnNoi_DiChanging(value);
					this.SendPropertyChanging();
					this._Noi_Di = value;
					this.SendPropertyChanged("Noi_Di");
					this.OnNoi_DiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noi_Den", DbType="VarChar(50)")]
		public string Noi_Den
		{
			get
			{
				return this._Noi_Den;
			}
			set
			{
				if ((this._Noi_Den != value))
				{
					this.OnNoi_DenChanging(value);
					this.SendPropertyChanging();
					this._Noi_Den = value;
					this.SendPropertyChanged("Noi_Den");
					this.OnNoi_DenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiVe", DbType="VarChar(30)")]
		public string TrangThaiVe
		{
			get
			{
				return this._TrangThaiVe;
			}
			set
			{
				if ((this._TrangThaiVe != value))
				{
					this.OnTrangThaiVeChanging(value);
					this.SendPropertyChanging();
					this._TrangThaiVe = value;
					this.SendPropertyChanged("TrangThaiVe");
					this.OnTrangThaiVeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoGhe", DbType="Int")]
		public System.Nullable<int> SoGhe
		{
			get
			{
				return this._SoGhe;
			}
			set
			{
				if ((this._SoGhe != value))
				{
					this.OnSoGheChanging(value);
					this.SendPropertyChanging();
					this._SoGhe = value;
					this.SendPropertyChanged("SoGhe");
					this.OnSoGheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaVe", DbType="Float")]
		public System.Nullable<double> GiaVe
		{
			get
			{
				return this._GiaVe;
			}
			set
			{
				if ((this._GiaVe != value))
				{
					this.OnGiaVeChanging(value);
					this.SendPropertyChanging();
					this._GiaVe = value;
					this.SendPropertyChanged("GiaVe");
					this.OnGiaVeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhiPhatsinh", DbType="Float")]
		public System.Nullable<double> PhiPhatsinh
		{
			get
			{
				return this._PhiPhatsinh;
			}
			set
			{
				if ((this._PhiPhatsinh != value))
				{
					this.OnPhiPhatsinhChanging(value);
					this.SendPropertyChanging();
					this._PhiPhatsinh = value;
					this.SendPropertyChanged("PhiPhatsinh");
					this.OnPhiPhatsinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhuyenMai", DbType="Float")]
		public System.Nullable<double> KhuyenMai
		{
			get
			{
				return this._KhuyenMai;
			}
			set
			{
				if ((this._KhuyenMai != value))
				{
					this.OnKhuyenMaiChanging(value);
					this.SendPropertyChanging();
					this._KhuyenMai = value;
					this.SendPropertyChanged("KhuyenMai");
					this.OnKhuyenMaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongGiaVe", DbType="Float")]
		public System.Nullable<double> TongGiaVe
		{
			get
			{
				return this._TongGiaVe;
			}
			set
			{
				if ((this._TongGiaVe != value))
				{
					this.OnTongGiaVeChanging(value);
					this.SendPropertyChanging();
					this._TongGiaVe = value;
					this.SendPropertyChanged("TongGiaVe");
					this.OnTongGiaVeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HANHKHACH_VE", Storage="_HANHKHACH", ThisKey="CMND_HK", OtherKey="CMND_HK", IsForeignKey=true)]
		public HANHKHACH HANHKHACH
		{
			get
			{
				return this._HANHKHACH.Entity;
			}
			set
			{
				HANHKHACH previousValue = this._HANHKHACH.Entity;
				if (((previousValue != value) 
							|| (this._HANHKHACH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HANHKHACH.Entity = null;
						previousValue.VEs.Remove(this);
					}
					this._HANHKHACH.Entity = value;
					if ((value != null))
					{
						value.VEs.Add(this);
						this._CMND_HK = value.CMND_HK;
					}
					else
					{
						this._CMND_HK = default(string);
					}
					this.SendPropertyChanged("HANHKHACH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LICHBAY_VE", Storage="_LICHBAY", ThisKey="MaCB,ThoiGianCatCanh,ThoiGianHaCanh", OtherKey="MaCB,ThoiGianCatCanh,ThoiGianHaCanh", IsForeignKey=true)]
		public LICHBAY LICHBAY
		{
			get
			{
				return this._LICHBAY.Entity;
			}
			set
			{
				LICHBAY previousValue = this._LICHBAY.Entity;
				if (((previousValue != value) 
							|| (this._LICHBAY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LICHBAY.Entity = null;
						previousValue.VEs.Remove(this);
					}
					this._LICHBAY.Entity = value;
					if ((value != null))
					{
						value.VEs.Add(this);
						this._MaCB = value.MaCB;
						this._ThoiGianCatCanh = value.ThoiGianCatCanh;
						this._ThoiGianHaCanh = value.ThoiGianHaCanh;
					}
					else
					{
						this._MaCB = default(string);
						this._ThoiGianCatCanh = default(Nullable<System.DateTime>);
						this._ThoiGianHaCanh = default(Nullable<System.DateTime>);
					}
					this.SendPropertyChanged("LICHBAY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
